In [1]:
import numpy as np

# 创建一个符合正态分布的10只股票5天的涨跌幅数据
stock_change = np.random.normal(0, 1, (10,5))

In [2]:
stock_change

array([[ 0.47514819,  0.46806469,  1.3761138 , -0.18020441, -1.82316717],
       [-0.22415871,  0.72813948,  0.67841993, -0.85328684, -0.26643303],
       [ 0.85377707,  0.94387033,  1.19658083,  0.29581118,  0.92552412],
       [-0.53417391, -1.1165484 ,  0.63604437, -1.44951744, -0.92664868],
       [ 0.95953836,  1.77056298, -0.35170725, -2.97707628,  2.01333886],
       [-0.97311283,  0.07952776, -0.20991385,  0.57125349,  1.62425097],
       [ 0.21492865,  0.23367128, -0.18178194,  0.23027016,  0.07577162],
       [-0.5000672 ,  1.90727308, -0.53595561, -0.04363929,  0.26826586],
       [-0.43617001, -0.34059309, -0.3411575 , -0.76687503, -0.56142896],
       [-1.61326126,  0.65086761, -0.5407862 , -0.80889356,  0.31314814]])

In [3]:
import pandas as pd

# 一、DataFrame

## 结构：

In [4]:
pd.DataFrame(stock_change)

0         1         2         3         4
0  0.475148  0.468065  1.376114 -0.180204 -1.823167
1 -0.224159  0.728139  0.678420 -0.853287 -0.266433
2  0.853777  0.943870  1.196581  0.295811  0.925524
3 -0.534174 -1.116548  0.636044 -1.449517 -0.926649
4  0.959538  1.770563 -0.351707 -2.977076  2.013339
5 -0.973113  0.079528 -0.209914  0.571253  1.624251
6  0.214929  0.233671 -0.181782  0.230270  0.075772
7 -0.500067  1.907273 -0.535956 -0.043639  0.268266
8 -0.436170 -0.340593 -0.341158 -0.766875 -0.561429
9 -1.613261  0.650868 -0.540786 -0.808894  0.313148

In [5]:
stocks = ["股票{}".format(i) for i in range(1, 11)]

stocks

['股票1', '股票2', '股票3', '股票4', '股票5', '股票6', '股票7', '股票8', '股票9', '股票10']

In [6]:
pd.DataFrame(stock_change, index = stocks) # 添加行索引

0         1         2         3         4
股票1   0.475148  0.468065  1.376114 -0.180204 -1.823167
股票2  -0.224159  0.728139  0.678420 -0.853287 -0.266433
股票3   0.853777  0.943870  1.196581  0.295811  0.925524
股票4  -0.534174 -1.116548  0.636044 -1.449517 -0.926649
股票5   0.959538  1.770563 -0.351707 -2.977076  2.013339
股票6  -0.973113  0.079528 -0.209914  0.571253  1.624251
股票7   0.214929  0.233671 -0.181782  0.230270  0.075772
股票8  -0.500067  1.907273 -0.535956 -0.043639  0.268266
股票9  -0.436170 -0.340593 -0.341158 -0.766875 -0.561429
股票10 -1.613261  0.650868 -0.540786 -0.808894  0.313148

In [7]:
dates = pd.date_range(start="20250101", periods=5, freq='B') # pd专门的日期函数，这里freq的B表示只选择工作日，2025.1.4、2025.1.5为周末

dates

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-06',
               '2025-01-07'],
              dtype='datetime64[ns]', freq='B')

In [8]:
pd.DataFrame(stock_change, index = stocks, columns= dates) # 添加行索引、列索引

2025-01-01  2025-01-02  2025-01-03  2025-01-06  2025-01-07
股票1     0.475148    0.468065    1.376114   -0.180204   -1.823167
股票2    -0.224159    0.728139    0.678420   -0.853287   -0.266433
股票3     0.853777    0.943870    1.196581    0.295811    0.925524
股票4    -0.534174   -1.116548    0.636044   -1.449517   -0.926649
股票5     0.959538    1.770563   -0.351707   -2.977076    2.013339
股票6    -0.973113    0.079528   -0.209914    0.571253    1.624251
股票7     0.214929    0.233671   -0.181782    0.230270    0.075772
股票8    -0.500067    1.907273   -0.535956   -0.043639    0.268266
股票9    -0.436170   -0.340593   -0.341158   -0.766875   -0.561429
股票10   -1.613261    0.650868   -0.540786   -0.808894    0.313148

In [9]:
data = pd.DataFrame(stock_change, index = stocks, columns= dates)

In [10]:
data

2025-01-01  2025-01-02  2025-01-03  2025-01-06  2025-01-07
股票1     0.475148    0.468065    1.376114   -0.180204   -1.823167
股票2    -0.224159    0.728139    0.678420   -0.853287   -0.266433
股票3     0.853777    0.943870    1.196581    0.295811    0.925524
股票4    -0.534174   -1.116548    0.636044   -1.449517   -0.926649
股票5     0.959538    1.770563   -0.351707   -2.977076    2.013339
股票6    -0.973113    0.079528   -0.209914    0.571253    1.624251
股票7     0.214929    0.233671   -0.181782    0.230270    0.075772
股票8    -0.500067    1.907273   -0.535956   -0.043639    0.268266
股票9    -0.436170   -0.340593   -0.341158   -0.766875   -0.561429
股票10   -1.613261    0.650868   -0.540786   -0.808894    0.313148

## 属性：

In [11]:
data.shape # 属性shape

(10, 5)

In [12]:
data.index # 属性index (行索引)

Index(['股票1', '股票2', '股票3', '股票4', '股票5', '股票6', '股票7', '股票8', '股票9', '股票10'], dtype='object')

In [13]:
data.columns # 属性columns (列索引)

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-06',
               '2025-01-07'],
              dtype='datetime64[ns]', freq='B')

In [14]:
data.values # 属性values (值)

array([[ 0.47514819,  0.46806469,  1.3761138 , -0.18020441, -1.82316717],
       [-0.22415871,  0.72813948,  0.67841993, -0.85328684, -0.26643303],
       [ 0.85377707,  0.94387033,  1.19658083,  0.29581118,  0.92552412],
       [-0.53417391, -1.1165484 ,  0.63604437, -1.44951744, -0.92664868],
       [ 0.95953836,  1.77056298, -0.35170725, -2.97707628,  2.01333886],
       [-0.97311283,  0.07952776, -0.20991385,  0.57125349,  1.62425097],
       [ 0.21492865,  0.23367128, -0.18178194,  0.23027016,  0.07577162],
       [-0.5000672 ,  1.90727308, -0.53595561, -0.04363929,  0.26826586],
       [-0.43617001, -0.34059309, -0.3411575 , -0.76687503, -0.56142896],
       [-1.61326126,  0.65086761, -0.5407862 , -0.80889356,  0.31314814]])

In [15]:
data.T # 转置

股票1       股票2       股票3       股票4       股票5       股票6  \
2025-01-01  0.475148 -0.224159  0.853777 -0.534174  0.959538 -0.973113   
2025-01-02  0.468065  0.728139  0.943870 -1.116548  1.770563  0.079528   
2025-01-03  1.376114  0.678420  1.196581  0.636044 -0.351707 -0.209914   
2025-01-06 -0.180204 -0.853287  0.295811 -1.449517 -2.977076  0.571253   
2025-01-07 -1.823167 -0.266433  0.925524 -0.926649  2.013339  1.624251   

                 股票7       股票8       股票9      股票10  
2025-01-01  0.214929 -0.500067 -0.436170 -1.613261  
2025-01-02  0.233671  1.907273 -0.340593  0.650868  
2025-01-03 -0.181782 -0.535956 -0.341158 -0.540786  
2025-01-06  0.230270 -0.043639 -0.766875 -0.808894  
2025-01-07  0.075772  0.268266 -0.561429  0.313148

## 方法：

In [16]:
data.head() # 默认返回前5行，括号里加数字可以指定返回的行数

2025-01-01  2025-01-02  2025-01-03  2025-01-06  2025-01-07
股票1    0.475148    0.468065    1.376114   -0.180204   -1.823167
股票2   -0.224159    0.728139    0.678420   -0.853287   -0.266433
股票3    0.853777    0.943870    1.196581    0.295811    0.925524
股票4   -0.534174   -1.116548    0.636044   -1.449517   -0.926649
股票5    0.959538    1.770563   -0.351707   -2.977076    2.013339

*一般看数据的结构会用data.head()*

In [17]:
data.tail() # 默认返回后5行，括号里加数字可以指定返回的行数

2025-01-01  2025-01-02  2025-01-03  2025-01-06  2025-01-07
股票6    -0.973113    0.079528   -0.209914    0.571253    1.624251
股票7     0.214929    0.233671   -0.181782    0.230270    0.075772
股票8    -0.500067    1.907273   -0.535956   -0.043639    0.268266
股票9    -0.436170   -0.340593   -0.341158   -0.766875   -0.561429
股票10   -1.613261    0.650868   -0.540786   -0.808894    0.313148

## 索引的设置：

### 1、修改行列索引值

In [18]:
data.head()

2025-01-01  2025-01-02  2025-01-03  2025-01-06  2025-01-07
股票1    0.475148    0.468065    1.376114   -0.180204   -1.823167
股票2   -0.224159    0.728139    0.678420   -0.853287   -0.266433
股票3    0.853777    0.943870    1.196581    0.295811    0.925524
股票4   -0.534174   -1.116548    0.636044   -1.449517   -0.926649
股票5    0.959538    1.770563   -0.351707   -2.977076    2.013339

In [19]:
data.index[2] # pandas不能单独修改某一个索引

'股票3'

In [20]:
stock_ = ["股票_{}".format(i) for i in range(11,21)]
stock_

['股票_11',
 '股票_12',
 '股票_13',
 '股票_14',
 '股票_15',
 '股票_16',
 '股票_17',
 '股票_18',
 '股票_19',
 '股票_20']

In [21]:
data.index = stock_ # 只能整体修改
data.head()

2025-01-01  2025-01-02  2025-01-03  2025-01-06  2025-01-07
股票_11    0.475148    0.468065    1.376114   -0.180204   -1.823167
股票_12   -0.224159    0.728139    0.678420   -0.853287   -0.266433
股票_13    0.853777    0.943870    1.196581    0.295811    0.925524
股票_14   -0.534174   -1.116548    0.636044   -1.449517   -0.926649
股票_15    0.959538    1.770563   -0.351707   -2.977076    2.013339

### 2、重设索引

In [22]:
data.reset_index() # 重新进行行索引

index  2025-01-01 00:00:00  2025-01-02 00:00:00  2025-01-03 00:00:00  \
0  股票_11             0.475148             0.468065             1.376114   
1  股票_12            -0.224159             0.728139             0.678420   
2  股票_13             0.853777             0.943870             1.196581   
3  股票_14            -0.534174            -1.116548             0.636044   
4  股票_15             0.959538             1.770563            -0.351707   
5  股票_16            -0.973113             0.079528            -0.209914   
6  股票_17             0.214929             0.233671            -0.181782   
7  股票_18            -0.500067             1.907273            -0.535956   
8  股票_19            -0.436170            -0.340593            -0.341158   
9  股票_20            -1.613261             0.650868            -0.540786   

   2025-01-06 00:00:00  2025-01-07 00:00:00  
0            -0.180204            -1.823167  
1            -0.853287            -0.266433  
2             0.295811             0.925524  
3            -1.449517            -0.926649  
4            -2.977076             2.013339  
5             0.571253             1.624251  
6             0.230270             0.075772  
7            -0.043639             0.268266  
8            -0.766875            -0.561429  
9            -0.808894             0.313148

In [23]:
data.reset_index().shape

(10, 6)

In [24]:
data.reset_index(drop=True) # 扔掉索引列，默认drop=False

2025-01-01  2025-01-02  2025-01-03  2025-01-06  2025-01-07
0    0.475148    0.468065    1.376114   -0.180204   -1.823167
1   -0.224159    0.728139    0.678420   -0.853287   -0.266433
2    0.853777    0.943870    1.196581    0.295811    0.925524
3   -0.534174   -1.116548    0.636044   -1.449517   -0.926649
4    0.959538    1.770563   -0.351707   -2.977076    2.013339
5   -0.973113    0.079528   -0.209914    0.571253    1.624251
6    0.214929    0.233671   -0.181782    0.230270    0.075772
7   -0.500067    1.907273   -0.535956   -0.043639    0.268266
8   -0.436170   -0.340593   -0.341158   -0.766875   -0.561429
9   -1.613261    0.650868   -0.540786   -0.808894    0.313148

In [25]:
data.reset_index(drop=True).shape

(10, 5)

### 3、设置新索引

In [26]:
# 可以直接用字典设置DataFrame

df = pd.DataFrame({'month': [1,4,7,10],
                   'year': [2022,2023,2024,2025],
                   'sale': [30,40,50,60]})

In [27]:
df

month  year  sale
0      1  2022    30
1      4  2023    40
2      7  2024    50
3     10  2025    60

In [28]:
# 单索引

df.set_index("year", drop=True) # drop默认为True，删除作为索引的列

month  sale
year             
2022      1    30
2023      4    40
2024      7    50
2025     10    60

In [29]:
df.set_index("year", drop=False) # drop=False，保留作为索引的列

month  year  sale
year                   
2022      1  2022    30
2023      4  2023    40
2024      7  2024    50
2025     10  2025    60

In [30]:
# 多索引，具有multiindex的DataFrame

new_df = df.set_index(["year", "month"])
new_df

sale
year month      
2022 1        30
2023 4        40
2024 7        50
2025 10       60

In [31]:
new_df.index

MultiIndex([(2022,  1),
            (2023,  4),
            (2024,  7),
            (2025, 10)],
           names=['year', 'month'])

### 4、MultiIndex

In [32]:
new_df.index.names # 属性names

FrozenList(['year', 'month'])

In [33]:
new_df.index.levels

FrozenList([[2022, 2023, 2024, 2025], [1, 4, 7, 10]])

# 二、Series

## 结构：

In [34]:
data

2025-01-01  2025-01-02  2025-01-03  2025-01-06  2025-01-07
股票_11    0.475148    0.468065    1.376114   -0.180204   -1.823167
股票_12   -0.224159    0.728139    0.678420   -0.853287   -0.266433
股票_13    0.853777    0.943870    1.196581    0.295811    0.925524
股票_14   -0.534174   -1.116548    0.636044   -1.449517   -0.926649
股票_15    0.959538    1.770563   -0.351707   -2.977076    2.013339
股票_16   -0.973113    0.079528   -0.209914    0.571253    1.624251
股票_17    0.214929    0.233671   -0.181782    0.230270    0.075772
股票_18   -0.500067    1.907273   -0.535956   -0.043639    0.268266
股票_19   -0.436170   -0.340593   -0.341158   -0.766875   -0.561429
股票_20   -1.613261    0.650868   -0.540786   -0.808894    0.313148

In [35]:
sr = data.iloc[1, :] # 提取带索引的一维数组，也就是Series
sr

2025-01-01   -0.224159
2025-01-02    0.728139
2025-01-03    0.678420
2025-01-06   -0.853287
2025-01-07   -0.266433
Freq: B, Name: 股票_12, dtype: float64

## 属性：

In [36]:
sr.index # 属性index，提取（行）索引

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-06',
               '2025-01-07'],
              dtype='datetime64[ns]', freq='B')

In [37]:
type(sr.index)

pandas.core.indexes.datetimes.DatetimeIndex

In [38]:
sr.values # 属性values，输出一维数组

array([-0.22415871,  0.72813948,  0.67841993, -0.85328684, -0.26643303])

In [39]:
type(sr.values) # 输出是ndarray

numpy.ndarray

## 方法：

### 创建Series

In [40]:
# 用一维数组创建

# pd.Series(np.arange(10)) 
pd.Series(np.arange(3, 9, 2), index=['a', 'b', 'c'])

a    3
b    5
c    7
dtype: int64

In [41]:
# 用字典创建

pd.Series({'a': 0, 'b': 2, 'c': 3})

a    0
b    2
c    3
dtype: int64